## ssh server


alias jekyll-server='cd /Users/4kkane/Documents/github/4kkane.github.io; jekyll server &'
##

alias ll='ls -l'
##alias code='cd /Users/4kkane/Documents/code'
alias doc='cd /Users/4kkane/Documents/doc'


## set env

export CLICOLOR=1
export LSCOLORS=ExGxFxdaCxDaDahbadeche
export GEM_HOME="$HOME/.gem"

autoload -U colors && colors
PROMPT="%{$fg_bold[cyan]%}%n%{$reset_color%}@%{$fg_bold[cyan]%}%m %{$fg_bold[green]%}%2~  %{$reset_color%}%#"

## java set env
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home
export CLASSPAHT=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
export PATH=$JAVA_HOME/bin:$PATH:


export M2_HOME=/Users/4kkane/Documents/tools/apache-maven-3.6.0
export PATH=$PATH:$M2_HOME/bin


## go
# 配置 GOPROXY 环境变量
export GOPROXY=https://proxy.golang.com.cn,direct
# 还可以设置不走 proxy 的私有仓库或组，多个用逗号相隔（可选）

export PATH=$PATH:/usr/local/go/bin:/Users/4kkane/go/bin
export GOPATH=$HOME/go
# mysql
export MYSQL_HOME=/usr/local/mysql
export PATH=$PATH:$MYSQL_HOME/bin

# python

alias python2=/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
alias python3=/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10
alias python=python3
alias pip=/Library/Frameworks/Python.framework/Versions/3.10/bin/pip

# rust
export PATH="$HOME/.cargo/bin:$PATH"

# node
#
#export NVM_DIR="$HOME/.nvm"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# google

. "$HOME/.local/bin/env"
