#!/bin/bash

# export 

mysqldump  -h127.0.0.27 -P3358 -uroot -proot@123456 -P3358  --databases 4kkane_db --tables t_kkb_goods  --skip-lock-tables > t_kkb_goods.sql

# import 

mysql -h127.0.0.27 -P3358 -uroot -proot@123456  4kkane_db -A
use 4kkane_db;
source  kkb_goods.sql ;



